name: Check Docker image build

on:
  push:
    branches-ignore:
      - main

jobs:

  build-test-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: rust-1.58
        uses: docker/build-push-action@v2
        with:
          context: ./rust/
          build-args: RUSTC_VERSION=1.58
          pull: true
          push: false
          tags: test-build

      - name: rust-actions-runner-1.58
        uses: docker/build-push-action@v2
        with:
          context: ./rust-actions-runner/
          build-args: RUST_VERSION=1.58
          pull: true
          push: false
          tags: test-build
